# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_pinout.xdc

# Block Designs: bd/simple_image/simple_image.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_image || ORIG_REF_NAME==simple_image} -quiet] -quiet

# IP: bd/simple_image/ip/simple_image_processing_system7_0_0/simple_image_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_image_processing_system7_0_0 || ORIG_REF_NAME==simple_image_processing_system7_0_0} -quiet] -quiet

# IP: bd/simple_image/ip/simple_image_axi_gpio_0_0/simple_image_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_image_axi_gpio_0_0 || ORIG_REF_NAME==simple_image_axi_gpio_0_0} -quiet] -quiet

# IP: bd/simple_image/ip/simple_image_ps7_0_axi_periph_0/simple_image_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_image_ps7_0_axi_periph_0 || ORIG_REF_NAME==simple_image_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/simple_image/ip/simple_image_rst_ps7_0_50M_0/simple_image_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_image_rst_ps7_0_50M_0 || ORIG_REF_NAME==simple_image_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/simple_image/ip/simple_image_pixel_mb_mem_0_0/simple_image_pixel_mb_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_image_pixel_mb_mem_0_0 || ORIG_REF_NAME==simple_image_pixel_mb_mem_0_0} -quiet] -quiet

# IP: bd/simple_image/ip/simple_image_xbar_0/simple_image_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_image_xbar_0 || ORIG_REF_NAME==simple_image_xbar_0} -quiet] -quiet

# IP: bd/simple_image/ip/simple_image_auto_pc_0/simple_image_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_image_auto_pc_0 || ORIG_REF_NAME==simple_image_auto_pc_0} -quiet] -quiet

# XDC: bd/simple_image/simple_image_ooc.xdc
